### PR TITLE
Add Bubble as special targets for special run configuration

### PR DESCRIPTION
**Pull request by feliciahalim**
@domainexpert the extended configuration allow bubble program to run with max time 120s.

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim Thank you! I think it would be useful to add a little explanation in the header comment on the various `make` targets for running with example-specific configurations, such as `tr`, `bubble`, `echo`, and `tr_nosyscall.tr0`, `bubble9.bubble0`, `echo_small.echo0` (for example)?

**Comment by feliciahalim** [comment]
@domainexpert Thanks for the suggestion. Do you mean the comment like this "Please run `make bubble` to run bubble examples including `(bubble9.c, bubble12.c)`" ?

**Comment by domainexpert** [comment]
@feliciahalim Yes, maybe also `make bubble9.bubble0` to run just `bubble9.c` with the specific configuration. ... Just so that we don't forget as things get more and more complex.

**Comment by feliciahalim** [comment]
@domainexpert I have added some comments on the header file. Thanks.

**Comment by domainexpert** [comment]
@feliciahalim It's really awesome: Thank you so much.

**Pull request merged**
