### PR TITLE
adding binary-chop folder containng WCET benchmark

### PR DESCRIPTION
**Pull request by rasoolmaghareh**

### CODE REVIEW

**Comment by domainexpert** [comment]
@rasoolmaghareh Just a small thing: Perhaps you would like to change the folder name to `binary-chop` as discussed? I'm actually fine if you want to keep it as is. You can do:
```
git mv binary_chop binary-chop
```

**Comment by rasoolmaghareh** [comment]
Changed binary_chop to binary-chop

**Comment by domainexpert** [comment]
@rasoolmaghareh It might be a good idea to add a short description about the new `binary-chop` directory in `README.md`, as a new list item between "Copyright ..." and "Running".

**Comment by rasoolmaghareh** [comment]
I added a short description about the binary-chop directory in README.md

**Comment by domainexpert** [comment]
Thank you @rasoolmaghareh .

**Pull request merged**
