### PR TITLE
Preserve the integrity of non-shared .gcda for robustness

### PR DESCRIPTION
**Pull request by feliciahalim**
Suppose that we modify Tracer-X in-between coreutils runs, although on the same coreutils program, the coverage result may differ. Reusing the .gcda from the previous run before Tracer-X modification may confuse the person doing the experiment.

Thanks @domainexpert for the advice.

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim I've seen some sequences of `rm` followed by `mv` such as at Lines 222-223. The `rm` is unnecessary and the `mv` should be replaced with `mv -f` to force the overwriting of the copy target. In general, I would recommend the use of `-f` option for `cp`, `mv`, `rm` in `Makefile`s as some users may alias those commands to the query version, e.g., aliasing `cp` to `cp -i` such that whenever the copy target exists, the user is asked to confirm the overwriting. This is disadvantageous to be used in a `Makefile` as the `make` execution will suspend asking the user to answer yes/no on some file operation they are likely not to be sure about. `-f` overrides this behavior such that the copy target gets automatically overwritten by default.

**Comment by domainexpert** [comment]
@feliciahalim Thank you for the work. I think it may also be useful to temporarily save the shared files `copy.gcda`, `cp-hash.gcda`, `chown-core.gcda` and `remove.gcda`.

**Comment by feliciahalim** [comment]
@domainexpert Thank you very much for the recommendation. I would like to ask about `mv`, because I see `GCOV` objects of mv is "`mv remove copy cp-hash`" . There are `mv.gcda, remove.gcda, copy.gcda`, and `cp-hash.gcda`. Which is one of `gcda mv`used? or there are multiple `gcda` being used?  This question is also applies to cp since cp has 2 possible gcda `copy`  and `cp-hash` Thanks.

**Comment by feliciahalim** [comment]
@domainexpert Other than that, I assume the gcda is the first word of GCOV objects. For example, 

```
if [ $* = "arch" ]; then \
        GCOV_OBJECTS="uname uname-arch" ; \

```

I assume the `gcda` is uname. Is my assumption is true? Thank you.

**Comment by domainexpert** [comment]
@feliciahalim Regarding your earlier comment, mv potentially uses all of mv.gcda, remove.gcda, copy.gcda and cp-hash.gcda, since these are object files containing the binary code that is executed when the executable `mv` itself is run. In other words, the code for `mv` is spread among mv.o, remove.o, copy.o, cp-hash.o, as well as the system library, but let's ignore system library. So, it seems to me a "coverage" for mv should then be a coverage of all of those files.

**Comment by domainexpert** [comment]
@feliciahalim Regarding your second comment, what you say is "almost" true for uname, as uname-uname.c contains no function: it has only two lines of code. The bulk of the code itself is in uname.c, however, in general as with the earlier comment, the code can be spread among those files.

**Comment by domainexpert** [comment]
@feliciahalim Please note that Lines 217 and 325 of join/Makefile have for loops that run `gcov` on all the .gcda files.

**Comment by feliciahalim** [comment]
@domainexpert `gcda` seems reproduced everytime `klee-replay`commands are executed. To make sure we only use the new `gcda`, I propose we remove the all `.gcda` files before and after `klee-replay`commands are executed.  I have pushed this in the latest commit.

**Comment by domainexpert** [comment]
@feliciahalim Thank you! Would you please remove the end backslash at Lines 199 and 273 as they are the last lines in their respective targets?

**Comment by feliciahalim** [comment]
@domainexpert  I have updated the Makefile by removing the end of backslash at lines 199 and 273. Thank you.

**Comment by domainexpert** [comment]
@feliciahalim I did a test run and it seems this is working.

**Pull request merged**
