### PR TITLE
Coreutils Cleanup and Run Automation

### PR DESCRIPTION
**Pull request by feliciahalim**
As we have discussed, we will use `Coreutils -6.10` instead of `scalability` folder. In this PR, I have removed `Coreutils-6.11`and build `Coreutils -6.10` based on http://klee.github.io/tutorials/testing-coreutils/ step 1 and step 2. 
To generate .bc files from `Coreutils -6.10`, I add folder `whole-program-llvm`. The steps are:

```
cd coreutils-6.10/obj-llvm/src
/klee-examples/whole-program-llvm/extract-bc <filename>
```

Then, it would generate .bc file for specific program and we can run tracer-x to execute this `.bc` file.
@domainexpert  I actually plan to create a Makefile in coreutils-6.10/obj-llvm/src for auto-generating `.bc`file and run it with tracer-x. But, there is also a Makefile inside the folder. Do you have any suggestion?

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim Regarding your question, I would suggest for now the use of shell scripts. We can create a new folder called `scripts` and put bash scripts there, say, `scripts/run-coreutils`, When `scripts/run-coreutils` is executed, it will build and execute `coreutils-6.10`. If you agree to go ahead with scripts, please do not forget to put some explanation on their usage in `README.md`.

**Comment by domainexpert** [comment]
@feliciahalim Thank you! I think it is best not to include the built Coreutils 6.10, but instead use a shell (bash) script to build it, and then extract the llvm bc. Also, instead of including whole-program-llvm in this repository, we could get the shell script to clone it for us, and then extract the bc for all programs in the coreutils, all done automatically. A shell script essentially command lines to be executed by the shell. An example is https://github.com/tracer-x/tracer/blob/master/dist/tracer. The first line of the command is usually `#!/bin/bash` which specifies the interpreter that executes the script.

**Comment by domainexpert** [comment]
@feliciahalim An alternative to script is to move `coreutils-6.10` directory within another directory that contains a `Makefile`, perhaps named just `coreutils`. So here we could create a new `Makefile` that would build Coreutils 6.10, clone whole-program-llvm, and extract the bitcode. I think this solution may be better than using scripts as it is more conforming to how other subdirectories are handled (using `Makefile`).

**Comment by feliciahalim** [comment]
@domainexpert  Thank you very much for the feedback. I followed your suggestion by moving `coreutils-6.10`into `coreutils` and creating `Makefile` in there. I actually did not clone the `whole-program-llvm` by using Makefile, but provided `whole-program-llvm` together in the `coreutils`. The reason is if the clone process of `whole-program-llvm` takes place when executing Makefile. It's quite hard to check whether the clone was successful because sometimes the clone process might not successful because of internet connection. I also avoiding to clone whole-program-llvm several times. I have explained in the README file inside `coreutils` folder that indicates `whole-program-llvm` is a wrapper script.

To try the Makefile, please use this new branch: https://github.com/tracer-x/klee/tree/cat . I use `cat` instead of `echo` because last time my computer freeze when I executed `echo`.

Please let me know what you think.

**Comment by domainexpert** [comment]
@feliciahalim I still need to look some more, but my first comment is that I think we could probably do away with the top-level `Coreutils`, `coreutils-6.10`, and `whole-program-llvm` directories.

**Comment by domainexpert** [comment]
@feliciahalim I think `coreutils/Makefile~` need not be included in the commit.

**Comment by domainexpert** [comment]
@feliciahalim `coreutils/whole-program-llvm` is empty. In any case, I think it is best to make it the responsibility of the user to clone `whole-program-llvm` themselves, and have the user specify its location in the `Makefile`.

**Comment by domainexpert** [comment]
@feliciahalim If there isn't much to write in `coreutils/README`, I suggest moving its content to the top-level `README.md` under a new **coreutils** item in the listed subdirectories.

**Comment by domainexpert** [comment]
@feliciahalim In the top-level `README.md`, I suggest renaming **coreutils-6.10** to the new **coreutils** item and remove the item **coreutils-6.11**.

**Comment by feliciahalim** [comment]
@domainexpert Thank you for the feedback. I agree to remove `whole-program-llvm` from `coreutils` folder and make it the responsibility of the user to clone `whole-program-llvm` by adjusting the `Makefile`. I noted it as a prerequisite in the `README` file. I have also removed top-level `Coreutils`, `coreutils-6.10,` and `whole-program-llvm` directories.

**Comment by domainexpert** [comment]
@feliciahalim Thank you! Again I think it would be good to add a little fix to the top-level `README.md` to synchronize it with the new directory structure, as I mentioned before. Maybe like renaming 'coreutils-6.10' to 'coreutils' in the list of subdirectories and remove the list item for 'coreutils-6.11'.

**Comment by domainexpert** [comment]
@feliciahalim I think the variable `KLEE_EXAMPLES` is not needed in `coreutils/Makefile` as in `README.md` we asked the user to run `make` after changing the current directory to a subdirectory (e.g., `coreutils`). So the `Makefile` will be executed with current directory `coreutils` anyway, and in the `cat` target, we can replace `cd ${KLEE_EXAMPLES}/${COREUTILS}/...` with just `cd ${COREUTILS}/...`.

**Comment by domainexpert** [comment]
@feliciahalim Thank you so much for the awesome work. I have added just a small polish to the build system of coreutils. In particular, I have moved the instruction from `coreutils/README` to `README.md` so that the instruction is harder to miss, with additonal information on older GNU Texinfo in case the user needs it. Also, I have made most things to be configurable in `Makefile.common`. Note that by setting `KLEE_HOME` in `Makefile.common`, various KLEE tools will be found without the need for setting `KLEE`, `KLEE_STATS`, etc.

**Comment by domainexpert** [comment]
@feliciahalim With the latest commits, `make cat` will automatically build `obj-lllvm` and `obj-gcov` only when they are nonexistent.

**Comment by domainexpert** [comment]
@feliciahalim Whenever you have time, would you please check that the latest commits work for you. Especially, in this version,  you or any user should only need to edit `Makefile.common` to suit your environment. Please in particular confirm that `make` successfully runs `cat` in `coreutils` subdirectory with the latest commits of tracer-x/klee#87. I'm happy for this branch to be merged already if it passed your test.

**Comment by feliciahalim** [comment]
@domainexpert Thank you very much for your work. I have updated with little fix in the remove directory command at`make cat`. Moreover, In the last page of `http://klee.github.io/docs/coreutils-experiments/,` there's recommended `sym-args` for each `coreutils` program. Therefore, I have updated the `Makefile`, so the current `Makefile` should work for all `coreutils` program with specific `sym-args`. Please let me know what you think. Thank you very much.

**Comment by feliciahalim** [comment]
@domainexpert I have also added a new target for running `coreutils` with KLEE STP solver. Please note in the `make` target I put re-assignment for some variables like this:

```
#$(eval KLEE = /home/felicia/git/original/klee/Release+Asserts/bin/klee)
    #$(eval KLEE_STATS= /home/felicia/git/original/klee/Release+Asserts/bin/klee-stats) 
    #$(eval KLEE_REPLAY= /home/felicia/git/original/klee/Release+Asserts/bin/klee-replay)
#$(eval KTEST_TOOL= /home/felicia/git/original/klee/Release+Asserts/bin/ktest-tool)
```

This assignment is because I separate source code of original KLEE and Tracer-x. By default, the variables are point to Tracer-X and I need to re-assign them to point to the source code of original KLEE. However, it might be different in your case. Therefore, I leave these lines commented.

I also put $(eval EXTRA_OPTIONS = ) which basically remove the `-interpolation-stat` flag since KLEE does not has the option.

**Comment by domainexpert** [comment]
@feliciahalim Thank you for a very useful modification! I've just made some polishing to simplify the `Makefile` and also so that we could conveniently use the sandbox and the minimalistic environment `test.env` mentioned in http://klee.github.io/docs/coreutils-experiments. The new usage instruction is quite similar to the usage for `basic` tests, and described in the `README.md`. That is, to run `echo`, for example, one executes `make echo.klee`. And to run KLEE/STP (non-Tracer-X) one simply executes `make echo.stpklee`. Please note that there is no need to have a separate installation for KLEE/STP as Tracer-X KLEE will run in KLEE/STP mode when `--select-solver=stp` is provided, Also, when `--select-solver=stp` is provided, `-interpolation-stat` will be ignored anyway, so there is no need to worry that the option is not supported.

There are some questions remain:
1. It is strange that the Coreutils [ program, for example, has no `.bc`, I think we need to figure out why and ask klee-dev about it if we could not obtain the bitcode file ourselves.
2. We may be able to use llvm-cov instead of gcov so that we do not need to do a second build of Coreutils in the `obj-gcov` subdirectory.

**Comment by domainexpert** [comment]
@feliciahalim I forgot to add that in `coreutils/Makefile`, one could opt to use the run options recommended in http://klee.github.io/docs/coreutils-experiments, by commenting/removing the second definition of `KLEE_COREUTILS_OPTIONS`.

**Comment by feliciahalim** [comment]
@domainexpert Thank you very much for very significant improvements. On your question, `[`program has no`.bc`, we could work with the rest `coreutils` program first and  ask`klee-dev` mailing list later. I think `gcov` is also fine since it's recommended way in KLEE instruction. We could use `llvm-cov`for programs other than `coreutils`.

I also have added `coverage log`in the makefile. Thank you.

**Comment by domainexpert** [comment]
@feliciahalim I think let's not use `-output-tree` for the first definition of `KLEE_COREUTILS_OPTIONS` for two reasons: 1) It no longer match what is given in http://klee.github.io/docs/coreutils-experiments which are the options closest to the options KLEE were run with for the experiments reported in 2008 OSDI paper, and 2) 3600 seconds (1 hour) run will likely to generate a huge tree beyond displaying.

**Comment by domainexpert** [comment]
@feliciahalim I would also suggest to remove `--output-tree` even for the second definition of `KLEE_COREUTILS_OPTIONS` with the 60 seconds run, but to provide the third alternative definiton for `KLEE_COREUTILS_OPTIONS` with `--max-time=10. --output-tree` options, so we only output the three for the 10s runs.

**Comment by domainexpert** [comment]
@feliciahalim I suggest renaming `CoverageLog.txt` to `GcovLog.txt` to make it clear which program produces the coverage information.

**Comment by feliciahalim** [comment]
@domainexpert coreutils run on 10s currently does not produce any subsumption. While, actually we need the tree to show subsumption. I am still experimenting the number of max-time which is still small enough for manageable display tree and also able to give subsumption. I will rename coverage log.

**Comment by domainexpert** [comment]
@feliciahalim Ok, in that case let's not add the third definition of `KLEE_COREUTILS_OPTIONS`. And maybe let's use `--output-tree` for the second definiton (with 60s timeout).

**Comment by domainexpert** [comment]
@feliciahalim I suggest changing `Create SVGs from *.dot files ...` in `coreutils/Makefile` to `Create SVG from tree.dot ...`

**Comment by domainexpert** [comment]
The suggested renaming of `CoverageLog.txt` to `GcovLog.txt` is actually implemented in PR #42 .

**Pull request merged**
